# Generated by Django 6.0.6 on 2026-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "處理中"),
                    ("success", "成功"),
                    ("failed", "失敗"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
