# Generated by Django 6.0.6 on 2026-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_product_is_active_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("新商品", "新商品"),
                    ("限量倒數", "限量倒數"),
                    ("熱賣", "熱賣"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
